# Sidekiq-cron will automatically load jobs specified in this file.
# More details here: https://github.com/sidekiq-cron/sidekiq-cron?tab=readme-ov-file#loading-jobs-from-schedule-file

preservation_backup:
  cron: "0 */1 * * *" # Every hour
  class: "EnqueueBulkPreservationBackupJob"
  describe: "Enqueues preservation backup jobs for assets that have not been backed up"
  queue: medium
  args:
    - 2000
ils_metadata:
  cron: "0 6 31 1,7 *" # 6am Jan and July 31
  class: "EnqueueBulkRefreshIlsMetadataJob"
  describe: "Enqueues ILS metadata refresh jobs for all items with a bibnumber"
  queue: low
