#
# Settings/Configuration shared among all environments.
#
# This configuration can be overridden in environment specific files.
#

# App Version
app_version: <%= ENV.fetch('APP_VERSION', nil)&.tr('-', '.') %>

# External Services
honeybadger:
  api_key: '12345'

# Item/Asset Resource Configuration
skip_ezid_metadata_update: false
supported_file_extensions:
  - .tif
  - .tiff
  - .pdf
  - .gz
  - .wav
  - .mov