#
# Settings/Configuration shared among all environments.
#
# This configuration can be overridden in environment specific files.
#

# External Services
honeybadger:
  api_key: nil

# Item/Asset Resource Configuration
skip_ezid_metadata_update: false
supported_file_extensions:
  - .tif
  - .tiff
  - .pdf
  - .gz
  - .wav
  - .mov