#
# Settings/Configuration shared among all environments.
#
# This configuration can be overridden in environment specific files.
#

# App Version
app_version: <%= ENV.fetch('APP_IMAGE_TAG', nil) %>

# App URL
app_url: <%= ENV.fetch('APP_URL', 'localhost:3000') %>

# Email for "System User"
system_user: 'system@apotheca.library.upenn.edu'

# External Services
honeybadger:
  api_key: '12345'

# Item/Asset Resource Configuration
skip_ezid_metadata_update: false
skip_preservation_backup: false
supported_file_extensions:
  - .tif
  - .tiff
  - .pdf
  - .gz
  - .wav
  - .mov
supported_mime_types:
  - application/pdf
  - application/gzip
  - audio/wav
  - audio/wave
  - audio/x-wav
  - audio/x-wave
  - audio/x-pn-wav
  - audio/vnd.wave
  - image/tiff
  - video/quicktime