#
# Settings/Configuration shared among all environments.
#
# This configuration can be overridden in environment specific files.
#

# App Version
app_version: <%= ENV.fetch('APP_IMAGE_TAG', nil) %>

# App URL
app_url: <%= ENV.fetch('APP_URL', 'localhost:3000') %>

# App URL
api_url: <%= ENV.fetch('API_URL', 'localhost:3000') %>

# Email for "System User"
system_user: 'system@apotheca.library.upenn.edu'

# Bootstrap version used to load CSS/JS files from a CDN
bootstrap_version: 5.3.8

# External Services
honeybadger:
  api_key: '12345'

# Item/Asset Resource Configuration
ezid_metadata_update:
  skip: false
preservation_backup:
  skip: false
publish:
  skip: false
supported_file_extensions:
  - .tif
  - .tiff
  - .pdf
  - .gz
  - .wav
  - .mov
supported_mime_types:
  - application/pdf
  - application/gzip
  - audio/wav
  - audio/wave
  - audio/x-wav
  - audio/x-wave
  - audio/x-pn-wav
  - audio/vnd.wave
  - image/tiff
  - video/quicktime
virus_check:
  skip: false
  size_threshold: 2000000000 # 2 GB

# Configuration used to load sample records.
sample_records:
  staging:
    host: digitalrepository-staging.library.upenn.edu
  production:
    host: digitalrepository.library.upenn.edu
    items:
      - 4aec6af0-c57e-4f0d-b1f4-7945f4bf7212
      - 362ba96f-2fab-4a35-bd42-98f6667da1d0
      - e90ec77f-008c-43e9-b720-d73db60fe3a3
      - 375a37c2-0cc4-4512-86f0-9113d9c80ca8
      - faa4493e-ec40-4520-9c13-41a1527609b6
