version: '3.4'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: [ "minio", "server", "--console-address", ":9001", "/data" ]
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  solr:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./solr:/colenda_admin_config
    command:
      - bash
      - "-c"
      - "precreate-core colenda_admin_dev /colenda_admin_config; precreate-core colenda_admin_test /colenda_admin_config; solr-foreground;"

volumes:
  db_data:
  minio_data:
  solr_data: