version: '3.4'

services:
  postgres:
    image: postgres:14.2
    environment:
      POSTGRES_PASSWORD: password
    ports:
      - '5432:5432'
    volumes:
      - db_data:/var/lib/postgresql/data
  minio:
    image: minio/minio:latest
    command: [ "minio", "server", "--console-address", ":9001", "/data" ]
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
  solr:
    image: solr:8.11
    ports:
      - "8983:8983"
    volumes:
      - solr_data:/var/solr
      - ./solr:/apotheca_config
    command:
      - bash
      - "-c"
      - "precreate-core apotheca_dev /apotheca_config; precreate-core apotheca_test /apotheca_config; solr-foreground;"
  fits:
    image: gitlab.library.upenn.edu/dld/digital-repository/fits-servlet:6d13f419
    ports:
      - "8080:8080"

volumes:
  db_data:
  minio_data:
  solr_data:
