---
sidekiq:
  instances:
    - name: default
      queues:
        - high
        - medium
        - low
      concurrency: 5
      replicas: 1
    - name: import
      queues:
        - import_high
        - import_medium
        - import_low
      concurrency: 10
      replicas: 1
