---
solr_collections:
  - name: apotheca-staging
    configset: apotheca
    replicas: 3
    shards: 1

solr_configsets:
  - name: "apotheca"
    path: "roles/apotheca/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_limits_cpu: "2"
solr_limits_mem: "6G"

solr_proxy_host: "apothe-stg01.library.upenn.int"

solr_custom_env_variables:
  SOLR_ADMIN_PASSWORD: "{{ apotheca_vault_values.secret.solr_password }}"
  SOLR_ADMIN_USERNAME: "{{ apotheca_vault_values.secret.solr_username }}"
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_HEAP: "4G"
  SOLR_JAVA_MEM: "-Xms5G -Xmx5G"

