---
is_development: false
project_root: "/opt/devops"

apotheca_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'apotheca/staging', engine_mount_point='kv-applications') }}"

hostsfile_entries:
  - ip: "127.0.0.1"
    hostname: "apothe-stg01.library.upenn.int"
    aliases:
      - "apothe-stg01"
