---

- name: Deploy Sidekiq
  community.docker.docker_stack:
    name: "apotheca"
    compose:
      - "{{ lookup('template', 'docker-compose.yml.j2', item=item) | from_yaml }}"
    state: present
  changed_when: false
  no_log: true
  loop: "{{ sidekiq.instances }}"
  environment:
    SIDEKIQ_PRO_CREDENTIALS: "{{ 'apotheca_sidekiq_pro_credentials_v' ~ apotheca_versioned_secrets.sidekiq_pro_credentials.version }}"
