---
- name: Create sidekiq dir
  file:
    path: "{{ project_root ~ '/sidekiq' }}"
    state: directory

- name: Copy base and dev docker-compose files
  copy:
    src: "../files/{{ item }}"
    dest: "{{ project_root ~ '/sidekiq/' }}"
  when: is_development | default (false) == true
  loop:
    - "docker-compose.yml"
    - "docker-compose.dev.yml"
  tags: dev_environment

- name: Deploy Sidekiq development environment
  docker_stack:
    name: "apotheca"
    compose:
      - "{{ project_root ~ '/sidekiq/docker-compose.yml' }}"
      - "{{ project_root ~ '/sidekiq/docker-compose.dev.yml' }}"
    state: present
  changed_when: false
  environment:
    APP_IMAGE_NAME: "{{ apotheca_image_name }}"
    APP_IMAGE_TAG: "{{ apotheca_image_tag }}"
    APP_PORT: "{{ apotheca_port }}"
    APP_URL: "{{ apotheca_url }}"
    DATABASE_NAME: "{{ postgres.database }}"
    DATABASE_PASSWORD: "{{ 'postgres_password_v' ~ postgres.versioned_secrets.password.version }}"
    DATABASE_USER: "{{ postgres.user }}"
    RAILS_ENV: "{{ apotheca_rails_env }}"
    REDIS_SIDEKIQ_USER: "sidekiq"
    REDIS_SIDEKIQ_PASSWORD: "{{ 'redis_sidekiq_password_v' ~ redis.versioned_configs.users_acl.users | selectattr('name', 'equalto', 'sidekiq') | map(attribute='version')  | join('') }}"
    REDIS_PORT: "{{ redis.port }}"
    REPLICAS: "{{ sidekiq.replicas }}"
    SOLR_URL: "{{ apotheca_solr_url }}"
  no_log: true
  when: is_development | default (false) == true
  tags: dev_environment

# Execute staging/production steps
- name: Copy docker-compose file
  copy:
    src: "../files/{{ item }}"
    dest: "{{ project_root ~ '/sidekiq/' }}"
  when: not is_development | default (false) == true
  loop:
    - "docker-compose.yml"

- name: Deploy Sidekiq
  docker_stack:
    name: "apotheca"
    compose:
      - "{{ project_root ~ '/sidekiq/docker-compose.yml' }}"
    state: present
  changed_when: false
  environment:
    APP_IMAGE_NAME: "{{ apotheca_image_name }}"
    APP_IMAGE_TAG: "{{ apotheca_image_tag }}"
    APP_PORT: "{{ apotheca_port }}"
    APP_URL: "{{ apotheca_url }}"
    DATABASE_NAME: "{{ postgres.database }}"
    DATABASE_PASSWORD: "{{ 'postgres_password_v' ~ postgres.versioned_secrets.password.version }}"
    DATABASE_USER: "{{ postgres.user }}"
    RAILS_ENV: "{{ apotheca_rails_env }}"
    REDIS_SIDEKIQ_USER: "sidekiq"
    REDIS_SIDEKIQ_PASSWORD: "{{ 'redis_sidekiq_password_v' ~ redis.versioned_configs.users_acl.users | selectattr('name', 'equalto', 'sidekiq') | map(attribute='version')  | join('') }}"
    REDIS_PORT: "{{ redis.port }}"
    REPLICAS: "{{ sidekiq.replicas }}"
    SOLR_URL: "{{ apotheca_solr_url }}"
  no_log: true
  when: not is_development | default (false) == true
