
version: "3.8"

services:
  minio:
    image: ${MINIO_IMAGE_NAME}:${MINIO_IMAGE_TAG}
    command: [ "minio", "server", "--console-address", ":9001", "/data" ]
    deploy:
      labels:
        - "traefik.enable=true"

        # Console
        - "traefik.http.routers.minio-console.rule=Host(`${MINIO_CONSOLE_URL}`)"
        - "traefik.http.routers.minio-console.entrypoints=web"
        - "traefik.http.routers.minio-console.service=minio-console"
        - "traefik.http.services.minio-console.loadbalancer.server.port=9001"

        # APi
        - "traefik.http.routers.minio.rule=Host(`${MINIO_SERVER_URL}`)"
        - "traefik.http.routers.minio.entrypoints=web"
        - "traefik.http.routers.minio.service=minio"
        - "traefik.http.services.minio.loadbalancer.server.port=9000"
      placement:
        constraints:
          - "node.labels.minio == true"
      replicas: ${MINIO_REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY_ID}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_ACCESS_KEY}
      MINIO_DOMAIN: ${MINIO_SERVER_URL}
      MINIO_SERVER_URL: http://${MINIO_SERVER_URL}
      MINIO_BROWSER_REDIRECT_URL: http://${MINIO_CONSOLE_URL}
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - traefik
    volumes:
      - minio_data:/data

networks:
  traefik:
    external: true

volumes:
  minio_data:
