version: "3.8"

services:
  clamav:
    image: ${CLAMAV_IMAGE_NAME}:${CLAMAV_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - "node.labels.clamav == true"
      replicas: ${CLAMAV_REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - traefik

networks:
  traefik:
    external: true

