Layout/TrailingEmptyLines:
  Enabled: false

Layout/InitialIndentation:
  Enabled: false

Lint/UselessAssignment:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Rails/FindEach:
  Enabled: false

Layout/LineLength:
  Enabled: false
