# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.2.5'

gem 'aasm'
gem 'after_commit_everywhere', '~> 1.0'
gem 'aws-sdk-s3'
gem 'bootsnap', require: false
gem 'bootstrap', '~> 5.3.1'
gem 'bootstrap_form', '~> 5.3.2'
gem 'cancancan'
gem 'clamby'
gem 'config', '~> 5.0'
gem 'devise'
gem 'dotiw'
gem 'dry-monads'
gem 'dry-transaction'
gem 'ezid-client'
gem 'factory_bot_rails'
gem 'faker'
gem 'faraday'
gem 'faraday-retry'
gem 'honeybadger'
gem 'iiif-presentation'
gem 'importmap-rails'
gem 'iso-639'
gem 'kaminari'
gem 'omniauth', '~> 2.0'
gem 'omniauth-rails_csrf_protection'
gem 'omniauth-saml', '~> 2.0'
gem 'pg', '~> 1.1'
gem 'puma', '~> 5.0'
gem 'rails', '~> 7.1'
gem 'rbtrace'
gem 'rouge', '~> 4.2'
gem 'rsolr'
gem 'ruby-vips'
gem 'sassc-rails' # Use Sass to process CSS
gem 'sidekiq'
gem 'sidekiq-cron'
gem 'sprockets-rails'
gem 'stimulus-rails'
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
gem 'upennlib-rubocop', '~> 1.0', require: false
gem 'valkyrie', '~> 3.0'
gem 'valkyrie-shrine'
gem 'view_component'

group :development, :test do
  gem 'byebug'
  gem 'debug', '~> 1.8'
  gem 'rspec-rails', '~> 6.0'
end

group :development do
  gem 'web-console'
end

group :test do
  gem 'capybara'
  gem 'cuprite'
  gem 'rspec-sidekiq'
  gem 'simplecov', require: false
  gem 'webmock'
end
