
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  post: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: colenda_admin_development

test:
  <<: *default
  database: colenda_admin_test

production:
  <<: *default
  database: colenda_admin_production
  username: colenda_admin
  password: <%= ENV["COLENDA_ADMIN_DATABASE_PASSWORD"] %>
