
default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: password
  host: localhost
  post: 5432
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: apotheca_development

test:
  <<: *default
  database: apotheca_test

production:
  <<: *default
  database: apotheca_production
  username: apotheca
  password: <%= ENV["APOTHECA_DATABASE_PASSWORD"] %>
