version: "3.8"

services:
  apotheca:
    deploy:
      labels:
        - "traefik.enable=true"

        - "traefik.http.routers.apotheca.entrypoints=web"
        - "traefik.http.routers.apotheca.rule=Host(`${APP_URL}`)"
        - "traefik.http.routers.apotheca.service=apotheca"
        - "traefik.http.services.apotheca.loadbalancer.server.port=${APP_PORT}"

        - "traefik.http.routers.apotheca.middlewares=apotheca_https"
        - "traefik.http.middlewares.apotheca_https.redirectscheme.scheme=https"
        - "traefik.http.middlewares.apotheca_https.redirectscheme.permanent=true"

        - "traefik.http.routers.apotheca_secure.entrypoints=websecure"
        - "traefik.http.routers.apotheca_secure.rule=Host(`${APP_URL}`)"
        - "traefik.http.routers.apotheca_secure.service=apotheca_secure"
        - "traefik.http.services.apotheca_secure.loadbalancer.server.port=${APP_PORT}"

        - "traefik.http.routers.apotheca_secure.tls=true"
        - "traefik.http.routers.apotheca_secure.tls.certresolver=letsencrypt"
    environment:
      APP_UID: ${UID:-1000}
      APP_GID: ${GID:-1000}
      CHROME_URL: "http://chrome:${CHROME_PORT}"
      SOLR_TEST_URL: "${SOLR_TEST_URL}"
      MINIO_URL: "http://minio:${MINIO_PORT}"
    healthcheck:
      retries: 20
      start_period: 5m
    volumes:
      - /apotheca/ansible/roles/apotheca/files/src/:/home/app
