version: "3.8"

services:
  fits:
    image: ${FITS_IMAGE_NAME}:${FITS_IMAGE_TAG}
    deploy:
      placement:
        constraints:
          - "node.labels.fits == true"
      replicas: ${FITS_REPLICAS}
      update_config:
        order: "start-first"
        parallelism: 1
    logging:
      driver: json-file
      options:
        max-file: "3"
        max-size: "10m"
    networks:
      - traefik

networks:
  traefik:
    external: true
