# frozen_string_literal: true

module Asset
  # Transaction that updates an Asset.
  class Update < Dry::Operation
    include Steps

    # TODO: maybe change async_derivative_generate to derivative_generation: :async/:sync
    def initialize(async_derivative_generation: true)
      @async_derivative_generation = async_derivative_generation
    end

    def call(id:, **attributes)
      resource = step find_asset(id)
      step require_updated_by(**attributes)
      step validate_file_extension(**attributes)
      step virus_check(**attributes)
      attributes = step store_file_in_preservation_storage(resource: resource, **attributes)

      change_set = step create_change_set(resource: resource, **attributes)
      step add_technical_metadata(change_set)
      step validate_expected_checksum(change_set)
      step mark_stale_derivatives(change_set)
      step unlink_stale_preservation_backup(change_set)
      step generate_derivatives(change_set)
      step add_preservation_events(change_set)
      step validate(change_set)
      resource = step save(change_set)

      record_event(resource)
      enqueue_derivative_job(resource)
      preservation_backup(resource)

      resource
    end

    # account for behavior in `around cleanup`
    def on_failure(failure)
      change_set = failure.fetch(:change_set, nil)

      if change_set&.changed?(:preservation_file_id) && change_set.preservation_file_id.present?
        Valkyrie::StorageAdapter.delete(id: change_set.preservation_file_id)
      end

      if change_set&.changed?(:preservation_copies_ids) && change_set.preservation_copies_ids.present?
        Valkyrie::StorageAdapter.delete(id: change_set.preservation_copies_ids.first)
      end

      delete_derivatives(change_set)
    end

    # Only delete derivatives if originally no derivatives were present. We don't want to delete the derivatives if
    # they were already present because external systems depend on them.
    def delete_derivatives(change_set)
      return if change_set.blank? || change_set.resource&.derivatives.present?

      change_set.derivatives.each do |derivative|
        Valkyrie::StorageAdapter.delete(id: derivative.file_id)
      end
    end

    # Wrapping save method in order to delete the old preservation file if a file update is successful.
    def save(change_set)
      # Storing ID for stale preservation backup.
      stale_preservation_backup = change_set.changed?(:preservation_copies_ids) ? change_set.resource.preservation_copies_ids&.first : nil

      result = super(change_set)

      # Delete stale preservation backup file
      if result.success? && stale_preservation_backup
        preservation_copy_storage = Valkyrie::StorageAdapter.find(:preservation_copy)
        preservation_copy_storage.delete(id: stale_preservation_backup)
      end

      result
    end

    def record_event(resource)
      ResourceEvent.record_event_for(resource: resource, event_type: :update_asset)
    end

    # Verify that file has original_filename that ends with a valid extension
    # @param [ActionDispatch::Http::UploadedFile|ImportService::S3Storage::File] file
    def validate_file_extension(**attributes)
      file = attributes[:file] || attributes['file']

      return Success(attributes) if file.blank?
      return Failure(error: :no_original_filename) if file.original_filename.blank?

      extension = File.extname(file.original_filename)

      if Settings.supported_file_extensions.include?(extension.downcase)
        Success(attributes)
      else
        Failure(error: :invalid_file_extension)
      end
    end

    # Validate that the expected_checksum matches the checksum generated by the technical metadata.
    def validate_expected_checksum(change_set)
      if change_set.expected_checksum.present?
        return Failure(error: :expected_checksum_provided_without_file) unless change_set.changed?(:preservation_file_id)
        return Failure(error: :expected_checksum_does_not_match) if change_set.expected_checksum != change_set.technical_metadata.sha256
      end

      Success(change_set)
    end

    # Stores file in preservation storage and adds in the system generated id to the list of
    # attributes passed on to the next step.
    #
    # @param [ActionDispatch::Http::UploadedFile|ImportService::S3Storage::File] file
    def store_file_in_preservation_storage(**attributes)
      file = attributes.delete(:file) || attributes.delete('file')

      if file
        file_resource = preservation_storage.upload(
          file: file,
          resource: attributes[:resource],
          original_filename: file.original_filename
        )

        attributes[:preservation_file_id] = file_resource.id

        # Explicitly set the original filename if file is not being migrated. If file is being migrated
        # store file's original filename in `migrated_filename` in order to record it properly in our
        # preservation events.
        if attributes[:migrated_from].blank?
          attributes[:original_filename] = file.original_filename
        else
          attributes[:migrated_filename] = file.original_filename
        end
      end

      Success(attributes)
    end

    def mark_stale_derivatives(change_set)
      if change_set.changed?(:preservation_file_id)
        change_set.derivatives.each do |derivative|
          derivative.stale = true
        end
      end
      Success(change_set)
    end

    # Removing connection to stale preservation backup.
    def unlink_stale_preservation_backup(change_set)
      # At this point we won't delete the stale preservation backup in case there is a problem saving the asset.
      change_set.preservation_copies_ids = [] if change_set.changed?(:preservation_file_id)

      Success(change_set)
    end

    # Generate derivatives as part of the update task to prevent retrieving the preservation file multiple times. By
    # default this step is skipped and the derivative files are generated asynchronously.
    #
    # Note: This method is a wrapper around the generate_derivative step defined in the container.
    def generate_derivatives(change_set)
      return Success(change_set) if @async_derivative_generation || change_set.preservation_file_id.blank?
      return Success(change_set) if change_set.derivatives.present? && change_set.derivatives.none?(&:stale)

      super(change_set)
    end

    # Enqueue a job to generates derivatives if they are missing or stale. Does not attempt to generate derivatives
    # for mime types where derivatives cannot be generated.
    #
    # @param [AssetResource] resource
    def enqueue_derivative_job(resource)
      return if resource.preservation_file_id.blank?
      return if resource.derivatives.present? && resource.derivatives.none?(&:stale)
      return unless DerivativeService::Asset::Derivatives.generate_for?(resource.technical_metadata.mime_type)

      GenerateDerivativesJob.perform_async(resource.id.to_s, resource.updated_by)
    end

    # Enqueue job to backup to S3 if backup is not present.
    def preservation_backup(resource)
      return if Settings.preservation_backup.skip
      return if resource.preservation_file_id.blank? || resource.preservation_copies_ids.present?

      PreservationBackupJob.perform_async(resource.id.to_s, resource.updated_by)
    end

    private

    def preservation_storage
      Valkyrie::StorageAdapter.find(:preservation)
    end
  end
end
