---
postgres:
  database: "{{ apotheca_vault_values.secret.postgres_database }}"
  dev_env:
    log_connections: "{{ apotheca_vault_values.secret.postgres_dev_env_log_connections }}"
    log_disconnections: "{{ apotheca_vault_values.secret.postgres_dev_env_log_disconnections }}"
    log_statement: "{{ apotheca_vault_values.secret.postgres_dev_env_log_statement }}"
  image:
    name: "{{ apotheca_vault_values.secret.postgres_image_name }}"
    tag: "{{ apotheca_vault_values.secret.postgres_image_tag }}"
  replicas: "{{ apotheca_vault_values.secret.postgres_replicas }}"
  versioned_secrets:
    password:
      value: "{{ apotheca_vault_values.secret.postgres_versioned_secrets_password_value }}"
      version: "{{ apotheca_vault_values.metadata.version }}"
  user: "{{ apotheca_vault_values.secret.postgres_user }}"
