---
postgres:
  database: "apotheca_dev"
  dev_env:
    log_connections: "on"
    log_disconnections: "on"
    log_statement: "all"
  image:
    name: "postgres"
    tag: "15.2-alpine"
  replicas: 1
  versioned_secrets:
    password:
      value: "{{ apotheca_vault_values.secret.postgres_versioned_secrets_password_value }}"
      version: "{{ apotheca_vault_values.metadata.version }}"
  user: "rails"