---
solr_collections:
  - name: apotheca-dev
    configset: apotheca
    replicas: 1
    shards: 1
  - name: apotheca-test
    configset: apotheca
    replicas: 1
    shards: 1

solr_collection_replicas: 1

solr_configsets:
  - name: "apotheca"
    path: "roles/apotheca/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_instances: 1

solr_limits_cpu: "2"
solr_limits_mem: "3G"

solr_proxy_host: "apotheca-dev.library.upenn.int"

solr_custom_env_variables:
  SOLR_ADMIN_PASSWORD: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_ADMIN_PASSWORD }}"
  SOLR_ADMIN_USERNAME: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_ADMIN_USERNAME }}"
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_HEAP: "2G"
  SOLR_JAVA_MEM: "-Xms2G -Xmx2G"