---
solr_collections:
  - name: apotheca-dev
    configset: "{{ apotheca_vault_values.secret.solr_configsets_name }}"
    replicas: "{{ apotheca_vault_values.secret.solr_collections_replicas }}"
    shards: "{{ apotheca_vault_values.secret.solr_collections_shards }}"
  - name: apotheca-test
    configset: "{{ apotheca_vault_values.secret.solr_configsets_name }}"
    replicas: "{{ apotheca_vault_values.secret.solr_collections_replicas }}"
    shards: "{{ apotheca_vault_values.secret.solr_collections_shards }}"

solr_collection_replicas: "{{ apotheca_vault_values.secret.solr_collection_replicas }}"

solr_configsets:
  - name: "{{ apotheca_vault_values.secret.solr_configsets_name }}"
    path: "{{ apotheca_vault_values.secret.solr_configsets_path }}"

solr_docker_image_tag: "{{ apotheca_vault_values.secret.solr_docker_image_tag }}"
solr_instances: "{{ apotheca_vault_values.secret.solr_instances }}"
solr_limits_cpu: "{{ apotheca_vault_values.secret.solr_limits_cpu }}"
solr_limits_mem: "{{ apotheca_vault_values.secret.solr_limits_mem }}"
solr_proxy_host: "{{ apotheca_vault_values.secret.solr_proxy_host }}"

solr_custom_env_variables:
  SOLR_ADMIN_PASSWORD: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_ADMIN_PASSWORD }}"
  SOLR_ADMIN_USERNAME: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_ADMIN_USERNAME }}"
  SOLR_ENABLE_AUTHENTICATION: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_ENABLE_AUTHENTICATION }}"
  SOLR_HEAP: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_HEAP }}"
  SOLR_JAVA_MEM: "{{ apotheca_vault_values.secret.solr_custom_env_variables_SOLR_JAVA_MEM }}"
