---
apotheca_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'apotheca/vagrant', engine_mount_point='kv-applications') }}"
ingress_ip: "10.10.2.137"
is_development: true
project_root: "/opt/devops"