---
apotheca_vault_values: "{{ lookup('community.hashi_vault.vault_kv2_get', 'apotheca/vagrant', engine_mount_point='kv-applications') }}"
ingress_ip: "{{ apotheca_vault_values.secret.ingress_ip }}"
is_development: "{{ apotheca_vault_values.secret.is_development }}"
project_root: "{{ apotheca_vault_values.secret.project_root }}"
