aws: &aws
  access_key_id: placeholder
  secret_access_key: placeholder
  endpoint: placeholder
  region: us-east-1
wasabi: &wasabi
  access_key_id: placeholder
  secret_access_key: placeholder
  endpoint: placeholder
  region: us-east-1
preservation_storage:
  <<: *aws
  bucket: preservation-staging
preservation_copy_storage:
  <<: *wasabi
  bucket: preservation-copy-staging
derivative_storage:
  <<: *aws
  bucket: derivatives-staging
iiif_derivative_storage:
  <<: *aws
  bucket: iiif-derivatives-staging
solr:
  url: <%= ENV['SOLR_URL'] %>
fits:
  url: <%= ENV['FITS_URL'] %>
marmite:
  url: http://mdproc.library.upenn.edu:9292
working_storage:
  sceti_digitized:
    <<: *aws
    bucket: sceti-short-term
  ceph:
    access_key_id: fake-id
    secret_access_key: fake-key
    endpoint: https://ceph.library.upenn.edu
    region: us-east-1
migration:
  storage: ceph
  colenda_url: https://colenda.library.upenn.edu

