#
# Settings/Configuration for test environment.
#

# Internal Services
solr:
  user: <%= DockerSecrets.lookup(:solr_username) %>
  password: <%= DockerSecrets.lookup(:solr_password) %>
  url: <%= ENV.fetch('SOLR_URL', 'http://solr:8983') %>
fits:
  url: <%= ENV.fetch('FITS_URL', 'http://fits') %>
redis:
  url: <%= ENV.fetch('REDIS_URL', 'localhost:6379') %>
  username: <%= ENV.fetch('REDIS_SIDEKIQ_USER', 'sidekiq') %>
  password: <%= DockerSecrets.lookup(:redis_sidekiq_password) %>

# External Services
ezid:
  default_shoulder: 'ark:/99999/fk4'
  user: <%= DockerSecrets.lookup(:ezid_user, 'apitest') %>
  password: <%= DockerSecrets.lookup(:ezid_password, 'apitest') %>
marmite:
  url: http://mdproc.library.upenn.edu:9292
honeybadger:
  api_key: <%= DockerSecrets.lookup(:honeybadger_api_key) %>

# File Storage
aws: &aws
  access_key_id: <%= DockerSecrets.lookup(:aws_access_key_id) %>
  secret_access_key: <%= DockerSecrets.lookup(:aws_secret_access_key) %>
  region: <%= DockerSecrets.lookup(:aws_region, 'us-east-1') %>
wasabi: &wasabi
  access_key_id: <%= DockerSecrets.lookup(:wasabi_access_key_id) %>
  secret_access_key: <%= DockerSecrets.lookup(:wasabi_secret_access_key) %>
  endpoint: https://s3.us-west-1.wasabisys.com
  region: us-west-1
  force_path_style: true
preservation_storage:
  <<: *aws
  bucket: upennlib-apotheca-preservation-staging
preservation_copy_storage:
  <<: *wasabi
  bucket: apotheca-preservation-copy-staging
derivative_storage:
  <<: *aws
  bucket: upennlib-apotheca-derivatives-staging
iiif_derivative_storage:
  <<: *aws
  bucket: upennlib-apotheca-iiif-derivatives-staging
iiif_manifest_storage:
  <<: *aws
  bucket: upennlib-apotheca-iiif-manifests-staging

# Bulk Import/Migration
working_storage:
  sceti-short-term:
    <<: *aws
    bucket: upennlib-sceti-short-term
  sceti-patron-requests:
    <<: *aws
    bucket: upennlib-sceti-patron-request
  ceph:
    access_key_id: <%= DockerSecrets.lookup(:ceph_access_key_id) %>
    secret_access_key: <%= DockerSecrets.lookup(:ceph_secret_access_key) %>
    endpoint: <%= DockerSecrets.lookup(:ceph_endpoint, 'http://ceph_endpoint_placeholder') %>
    region: us-east-1
    force_path_style: true
migration:
  storage: ceph
  colenda_url: https://colenda.library.upenn.edu

# Item/Asset Resource Configuration
ezid_metadata_update:
  skip: true
iiif:
  image_server:
    url: 'https://iiif-images-staging.library.upenn.edu/iiif/2'
    profile: 'http://iiif.io/api/image/2/level2.json'
  manifest:
    base_url: 'https://colenda-dev.library.upenn.edu/items/'
    item_link_base_url: 'https://colenda-dev.library.upenn.edu/catalog/'
publish:
  url: https://colenda-dev.library.upenn.edu
  token: <%= DockerSecrets.lookup(:colenda_publish_token, 'sample_token') %>
virus_check:
  skip: false
  size_threshold: 2000000000 # 2 GB