---
solr_collections:
  - name: apotheca
    configset: apotheca
    replicas: 3
    shards: 1

solr_configsets:
  - name: "apotheca"
    path: "roles/apotheca/files/src/solr/conf/"

solr_docker_image_tag: 9.3.0

solr_proxy_host: "apothe-prod01.library.upenn.int"

solr_custom_env_variables:
  SOLR_ENABLE_AUTHENTICATION: "yes"
  SOLR_ADMIN_USERNAME: "{{ apotheca_vault_values.secret.solr_username }}"
  SOLR_ADMIN_PASSWORD: "{{ apotheca_vault_values.secret.solr_password }}"
  # SOLR_JAVA_MEM: "-Xms4g -Xmx4g"
