minio: &minio
  access_key_id: minioadmin
  secret_access_key: minioadmin
  endpoint: http://127.0.0.1:9000
  region: us-east-1
preservation_storage:
  <<: *minio
  bucket: preservation-dev
preservation_copy_storage:
  <<: *minio
  bucket: preservation-copy-dev
derivative_storage:
  <<: *minio
  bucket: derivatives-dev
iiif_derivative_storage:
  <<: *minio
  bucket: iiif-derivatives-dev
solr:
  url: http://127.0.0.1:8983/solr/apotheca_dev
fits:
  url: http://localhost:8080/fits
marmite:
  url: http://mdproc.library.upenn.edu:9292
skip_ezid_metadata_update: true
