minio: &minio
  access_key_id: minioadmin
  secret_access_key: minioadmin
  endpoint: http://127.0.0.1:9000
preservation_storage:
  <<: *minio
  bucket: preservation-test
derivative_storage:
  <<: *minio
  bucket: derivatives-test
solr:
  url: http://127.0.0.1:8983/solr/colenda_admin_test
fits:
  url: http://localhost:8080/fits
marmite:
  url: https://marmite.library.upenn.edu:9292
