---
- name: "Provision Docker Swarm Cluster"
  hosts: docker_swarm_manager
  become: true
  tasks:
    - name: "Import Docker provisioning tasks"
      ansible.builtin.import_tasks: "provision_docker.yml"

- name: "Deploy application"
  hosts: docker_swarm_manager
  become: true
  gather_facts: true
  tasks:
    - name: "Import Traefik role"
      ansible.builtin.import_role:
        name: traefik
      tags: traefik
    - name: "Import Zookeeper role"
      ansible.builtin.import_role:
        name: zookeeper
      tags: zookeeper
    - name: "Import Zoonavigator role"
      ansible.builtin.import_role:
        name: zoonavigator
      tags: zoonavigator
      when: not is_development | default(false, true)
    - name: "Import Solr role"
      ansible.builtin.import_role:
        name: solr
      tags: solr
    - name: "Import Redis role"
      ansible.builtin.import_role:
        name: redis
      tags: redis
    - name: "Import FITS role"
      ansible.builtin.import_role:
        name: fits
      tags: fits
    - name: "Import ClamAV role"
      ansible.builtin.import_role:
        name: clamav
      tags: clamav
    - name: "Import PostgreSQL role"
      ansible.builtin.import_role:
        name: postgres
      tags: postgres
    - name: "Import MinIO role"
      ansible.builtin.import_role:
        name: minio
      tags: minio
      when: is_development | default(false, true)
    - name: "Import Apotheca role"
      ansible.builtin.import_role:
        name: apotheca
      tags: apotheca
    - name: "Import API role"
      ansible.builtin.import_role:
        name: api
      tags: api
    - name: "Import Sidekiq role"
      ansible.builtin.import_role:
        name: sidekiq
      tags: sidekiq
    - name: "Import Chrome role"
      ansible.builtin.import_role:
        name: chrome
      tags: chrome
      when: is_development | default(false, true)
  post_tasks:
    - name: Recursively remove project directory
      ansible.builtin.file:
        path: "{{ project_root }}"
        state: absent
    - name: Prune images that are older than 2+ hours
      community.docker.docker_prune:
        images: true
        images_filters:
          dangling: false
          until: 2h
      when: not is_development | default(false, true)
