---
- name: Create custom docker image
  community.docker.docker_image:
    build:
      args:
        RAILS_ENV: "{{ apotheca_rails_env }}"
      dockerfile: "Dockerfile"
      path: "/apotheca/ansible/roles/apotheca/files/src/"
      target: "development"
      pull: true
    force_tag: true
    force_source: true
    name: "{{ apotheca_image_name ~ ':' ~ apotheca_image_tag }}"
    source: build
    state: present
