---
- name: Create custom docker image using buildkit
  community.docker.docker_image_build:
    name: "{{ apotheca_image_name }}:{{ apotheca_image_tag }}"
    path: "/apotheca/ansible/roles/apotheca/files/src/"
    dockerfile: "Dockerfile"
    target: "development"
    secrets:
      - id: sidekiq_pro_credentials
        type: value
        value: "{{ dld_sidekiq_pro_vault_values.secret.credentials }}"
    args:
      RAILS_ENV: "{{ apothea_rails_env }}"