---
- name: Create custom docker image using buildkit
  ansible.builtin.shell:
    cmd: |-
      docker build --build-arg RAILS_ENV="{{ apotheca_rails_env }}" --target=development -t {{ apotheca_image_name }}:{{ apotheca_image_tag }} .
    chdir: "/apotheca/ansible/roles/apotheca/files/src/"
  environment:
    DOCKER_BUILDKIT: "true"

