---
- name: Create custom docker image
  community.docker.docker_image_build:
    name: "{{ apotheca_image_name ~ ':' ~ apotheca_image_tag }}"
    path: "/apotheca/ansible/roles/apotheca/files/src/"
    dockerfile: "Dockerfile"
    target: "development"
    secrets:
      - id: sidekiq_pro_credentials
        type: value
        value: "{{ apotheca_versioned_secrets.sidekiq_pro_credentials.value }}"
    args:
      RAILS_ENV: "{{ apotheca_rails_env }}"
